### ISSUE TITLE
slickR not working with markdown when tabs are used?

### ISSUE THREAD

**Issue by ahdee** [yonicd/slickR#46]
Hi I notice that the slider does not show up if it is placed in a tab that is not the first, for example below is a markdown in html.  The first slider will show up whilst the second will not.  Is there a workaround for this? I found several issues in stackoverflow but those seem to be rectifying shiny apps; is there a solution for a markdown? thanks!

```
#Data
# {.tabset}

## results 

```{r}
opts_dot_number <- settings(
        initialSlide = 0,
        slidesToShow = 1,
        slidesToScroll = 1,
        focusOnSelect = TRUE,
        dots = TRUE,
        adaptiveHeight =T 
        )
    
    
    slickR(
        obj = expfiles
        , padding=0 
        ,height=1200, 
      width=1200 ) 
```

```
## results2
{r second }
opts_dot_number <- settings(
        initialSlide = 0,
        slidesToShow = 1,
        slidesToScroll = 1,
        focusOnSelect = TRUE,
        dots = TRUE,
        adaptiveHeight =T 
        )
    
    
    slickR(
        obj = expfiles
        , padding=0 
        ,height=1200, 
      width=1200 ) 

```

```

**Comment by yonicd** [comment]
Thanks for opening the issue. 

Can you pleases supply a fully reproducible example.

**Comment by yonicd** [comment]
The sliders work for me on a `tabset`

````

---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(slickR)
```

## tab1 {.tabset}

### My first slider

This is the first slider

```{r}
slickR::slickR(obj=nba_team_logo$uri,height = 100)
```

### tab2

This is the second slider

```{r}
slickR::slickR(obj=nba_team_logo$uri,height = 100)
```

````

The second slider gets activated for some reason if you click on it (try an arrow). 

This doesn't seem to be a problem with `slickR` or the underlying `js` library, but the way that the tabs work with htmlwidgets.

**Comment by ahdee** [comment]
@yonicd thanks!  Sorry I was a bit busy yesterday to post an example. However I would've done the same.  Its showing up now. I think the issue was that I was not activating the arrows as you mentioned previously.  But it works when the arrows are pushed. I'm wondering now if there is an option in the setting to activate the first slide?  A side question. Is there anyway to make the arrows bigger or with different icon?   

```
opts_dot_number <- settings(
    initialSlide = 0,
    slidesToShow = 1,
    slidesToScroll = 1,
    focusOnSelect = TRUE, # I wonder if there is an option for auto load?
     arrows = T, ## bigger arrows or icon? 
    dots = TRUE
    )
```

**Comment by dan-reznik** [comment]
I am having the same issue. the caroussel initially appears empty and the only way to populate it with a first picture is to click on the right arrow. Is there a small piece of JS code that would simulate that event?

**Comment by yonicd** [comment]
Thanks for adding the comment, I’ll dig into it to see what can be done

**Comment by yonicd** [comment]
@dan-reznik that page you linked to initialized all the carousels for me (I didn’t see any tabs though)

**Comment by dan-reznik** [comment]
i removed them because they weren't working...

i just pushed a new version again with the tabsets (section 2), do take a
look.

dan

**Comment by yonicd** [comment]
i see it now. thanks for updating that.

**Comment by yonicd** [comment]
@RLesur any ideas on how this can be solved?

**Comment by dan-reznik** [comment]
thanks! this has been a source of frustration for some time.

dan

**Comment by dan-reznik** [comment]
Can some small JS snippet run at initialization which fakes arrow pushes
behind the scenes?

Dan

**Comment by yonicd** [comment]
javascript may be a bit tricky because you would need to know the slick sliders id up front and the way the id's are set up now by default the have a random stub to avoid conflicts in multiple slider outputs in the same html doc output.

**Comment by dan-reznik** [comment]
could you force it to have a certain name?

**Comment by yonicd** [comment]
one solution is this:

````
```{r}
slickR::slickR(obj=nba_team_logo$uri,height = 100) + 
  slickR::settings(autoplay = TRUE,autoplaySpeed = 1000)
```
````

it will force the slider to start up. the defaults of the slider are set to pause the autoplay when the mouse is hovering over any part of the slider.

**Comment by yonicd** [comment]
regarding the name. you can give unique stems for the id (ie instead of baseDiv) then use regex in the js to manipulate the slick

**Comment by dan-reznik** [comment]
i will try! thanks!

dan

**Comment by dan-reznik** [comment]
unfortunately it only works for the first tab not the other ones.

dan

**Comment by ahdee** [comment]
The very least I wonder if its possible to make the arrows BIGGER so that its very obvious.  May be a solution is to just put put a default message - Something like please scroll right to see data?

**Comment by dan-reznik** [comment]
it's too bad really. such a simple thing!

dan

**Comment by yonicd** [comment]
@dan-reznik here are three tabs first is regular other ones have autoplay.

````
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(slickR)
```

## Results {.tabset}

### Plots

We show a scatter plot in this section.

```{r}
slickR::slickR(obj=nba_team_logo$uri,height = 100)
```

### Tables 1

We show the data in this tab.

```{r}
slickR::slickR(obj = nba_team_logo$uri,
               height = 100) + 
  slickR::settings(autoplay = TRUE,
                   autoplaySpeed = 1000)
```

### Tables 2

We show the data in this tab.

```{r}
slickR::slickR(obj = nba_team_logo$uri,
               height = 100) + 
  slickR::settings(autoplay = TRUE,
                   autoplaySpeed = 1000)
```

````

**Comment by yonicd** [comment]
@ahdee to manipulate the arrows you have two arguments in the settings:

```r
slickR::settings(prevArrow = '<button type="button" class="slick-prev">Previous</button>',
                   nextArrow = '<button type="button" class="slick-next">Next</button>')
```

you would need to have some `css` knowledge to be able to use this, which is beyond the scope of this package.

**Comment by RLesur** [comment]
@yonicd I would try to detect when a tab is activated to refresh the slick element. For instance,

    ---
    title: "Untitled"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```
    
    ```{r}
    library(slickR)
    ```
    
    ## tab1 {.tabset}
    
    ### My first slider
    
    This is the first slider
    
    ```{r}
    slickR::slickR(obj=nba_team_logo$uri,height = 100)
    ```
    
    ### tab2
    
    This is the second slider
    
    ```{r}
    slickR::slickR(obj=nba_team_logo$uri,height = 100)
    ```
    
    ```{js, echo=FALSE}
    $('body').on('shown.bs.tab', function(e) {
      $(e.target).parents('.tabset')
                 .find('.active .slick-slider')
                 .each(function() {
                   this.slick.setPosition()
                  });
    });
    ```

I'm sure this can be improved.

**Comment by yonicd** [comment]
thanks @RLesur that works! I like your `find` a bit more than the one i hacked together :)

here is another example that @daattali helped me construct

````
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(slickR)
```

## Results {.tabset}

### Plots

We show a scatter plot in this section.

```{r}
slickR::slickR(obj=nba_team_logo$uri,height = 100)
```

### Tables

We show the data in this tab.

```{r}
slickR::slickR(obj = nba_team_logo$uri,height = 100)
```


### Tables 2

We show the data in this tab.

```{r}
slickR::slickR(obj = nba_team_logo$uri,height = 100)
```

```{js,echo = FALSE}
$(document).on('shown.bs.tab', 'a[data-toggle="tab"]', function (event) {
  $.each($("[class^=baseDiv]"),function(key,value) {
  value.slick.setPosition()
  })
})

```

````

**Comment by dan-reznik** [comment]
Yoni and Romain

Todah Rabbah, Merci Beaucoup

Will try it right away

Dan

**Comment by ahdee** [comment]
Thanks a bunch @yonicd  and @RLesur  this great and I think solves an important issue.  Also thanks for the css hack for the arrows; that is enough for me to work on as well! 
thanks!
