### ISSUE TITLE
Error thrown by HTMLTools

### ISSUE THREAD

**Issue by ColinConwell** [yonicd/slickR#48]
slickR's example code seems to have a conflict with htmltools.

`
slickR::slickR(
    list.files(file.path(getwd(),"assets"), full.names = TRUE, pattern = 'png'), 
    height = 200, width = '95%')
`
produces the following error:

Error in htmltools::tag(tag, varArgs, .noWS) : unused argument (.noWS)

Is this a versioning issue on my end or something else?

**Comment by yonicd** [comment]
please attach your session info

**Comment by ColinConwell** [comment]
Thanks for the rapid response; this seems to have done it.

Apologies for the repeat issue. My Google search had not shown the previous one.
