### ISSUE TITLE
slickR no longer available on CRAN

### ISSUE THREAD

**Issue by devhawkio** [yonicd/slickR#49]
Hello,
It appears that slickR has been removed from CRAN because the maintainer was uncontactable.
Is this the official slickR repo?

Thank you,
Bobby

**Comment by yonicd** [comment]
Thanks for the question.

Sorry for the inconvenience. 

The package was resubmitted a few days ago and is waiting approval by CRAN team.

Current master branch is what is sent to CRAN

**Comment by devhawkio** [comment]
Awesome, I will use the install_github command for now.
