### ISSUE TITLE
slickR shiny vignette broken

### ISSUE THREAD

**Issue by ismirsehregal** [yonicd/slickR#51]
I just tried to run the [slickR shiny vignette](https://cran.r-project.org/web/packages/slickR/vignettes/shiny.html) but it seems to be broken.

Once the `radioButtons` are used to switch to _stacked_ or _synch_ mode the `input$slick_output_current` isn't providing any data.
Also the lower carousel isn't rendered properly:

![screen](https://user-images.githubusercontent.com/36849480/107500198-2f6ef780-6b96-11eb-8955-79515ac751a3.gif)

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gdtools_0.2.3   svglite_1.2.3.2 slickR_0.5.0    xml2_1.3.2      shiny_1.6.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        rstudioapi_0.13   magrittr_2.0.1    xtable_1.8-4      R6_2.5.0          rlang_0.4.10     
 [7] fastmap_1.1.0     tools_4.0.3       jquerylib_0.1.3   withr_2.4.1       systemfonts_1.0.1 htmltools_0.5.1.1
[13] ellipsis_0.3.1    yaml_2.2.1        digest_0.6.27     lifecycle_0.2.0   crayon_1.4.0      later_1.1.0.1    
[19] sass_0.3.1        base64enc_0.1-3   htmlwidgets_1.5.3 promises_1.1.1    cachem_1.0.1      mime_0.9         
[25] compiler_4.0.3    bslib_0.2.4       jsonlite_1.7.2    httpuv_1.5.5    
```

---

```
library(shiny)
library(svglite)
library(slickR)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      
      sliderInput(inputId = "plot_num", 
                  label = "Number of Plots:", 
                  min = 1, max = 20, value = 5),
      
      sliderInput(inputId = "n_obs", 
                  label = "Number of observations:", 
                  min = 10, max = 500, value = 100),
      
      shiny::radioButtons('slick_type',
                          label = 'Carousel Type',
                          choices = c('single','stack','synch'),
                          selected = 'single',
                          inline = TRUE),
      
      shiny::verbatimTextOutput('current')
    ),
    mainPanel(
      
      slickROutput("slick_output",width='100%',height='200px')
      
    )
  )
)

server <- function(input, output) {
  
  # Create content for the carousel
  
  plots <- eventReactive(c(input$n_obs,input$plot_num),{
    
    replicate(input$plot_num,{
      
      xmlSVG({hist(rnorm(input$n_obs),
                   col = 'darkgray',
                   border = 'white')},
             standalone=TRUE)
      
    },simplify = FALSE)
  })
  
  # renderSlickR (We create the slickR objects here)
  
  output$slick_output <- renderSlickR({
    
    x <- slickR(plots(),
                slideId = 'myslick',
                height = 600,
                width = '50%') + 
      settings(slidesToShow=3,centerMode=TRUE)
    
    switch(input$slick_type,
           'single' = x,
           'stack'  = x %stack% x,
           'synch'  = x %synch% x
    )
    
  })
  
  # Observe the active slick
  
  # The htmlwidget is observed by shiny and information can be retrieved. 
  
  # Using the output name you set for the `renderSlick` object in this example
  # it is `output$slick_output`
  
  # Using this you can interact server-side "on click" of the active carousel
  # by accessing elements in `input$slick_output_current$`
  
  # `.clicked_slide`   : The index of the clicked element|
  # `.relative_clicked`: The relative position of the clicked element|
  # `.center_slide`    : The index of the center element|
  # `.total_slide`     : The total number of elements in the carousel|
  # `.active_slide`    : The ID of the active carousel|
  
  # We will store this information in a new reactive environment
  active_slick <- shiny::reactiveValues()
  
  shiny::observeEvent(input$slick_output_current,{
    clicked_slide    <- input$slick_output_current$.clicked
    relative_clicked <- input$slick_output_current$.relative_clicked
    center_slide     <- input$slick_output_current$.center
    total_slide      <- input$slick_output_current$.total
    active_slide     <- input$slick_output_current$.slide
    
    if(!is.null(clicked_slide)){
      active_slick$clicked_slide    <- clicked_slide
      active_slick$center_slide     <- center_slide
      active_slick$relative_clicked <- relative_clicked
      active_slick$total_slide      <- total_slide
      active_slick$active_slide     <- active_slide
    }
  })
  
  # Show in the UI the values in active_slick
  
  output$current <- renderText({
    l <- shiny::reactiveValuesToList(active_slick)
    paste(gsub('_',' ',names(l)), unlist(l),sep=' = ',collapse='\n')
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by yonicd** [comment]
thanks for opening the issue, will investigate

**Comment by yonicd** [comment]
This should fix the problem which was having the same ID for two elements in the app.

The reactive text will observing the carousels will be attached to the last carousel built ie if only 1 carousel the slick1 if two carousels it will track slick2

```r
  output$slick_output <- renderSlickR({
    
    x <- slickR(plots(),
                slideId = 'slick1',
                height = 600,
                width = '50%') + 
      settings(slidesToShow=3,centerMode=TRUE)

    y <- slickR(plots(),
                slideId = 'slick2',
                height = 600,
                width = '50%') + 
      settings(slidesToShow=3,centerMode=TRUE)    
    
    switch(input$slick_type,
           'single' = x,
           'stack'  = x %stack% y,
           'synch'  = x %synch% y
           )

  })
```

**Comment by ismirsehregal** [comment]
Thanks for the very fast update!

With the new version when i switch from _single_ to _stack_ all is fine. When I then switch to _synch_ I have 3 carousels, back to _stack_ and there are 4.

I'ts piling up new carousels.

**Comment by yonicd** [comment]
ha nice. i'll take another look

**Comment by yonicd** [comment]
try this commit https://github.com/yonicd/slickR/commit/417fd60e013b70540970c1b798897050c3580d2c it should accommodate multiple sliders in the same app including the observers to know which is active

**Comment by ismirsehregal** [comment]
Using your latest commit the vignette runs fine! Thanks for your time and effort!

I hope I'm not stressing this issue too much, but the following is still related to the shiny implementation:

Initially I came here due to this [SO question](https://stackoverflow.com/questions/66089815/slickr-shiny-r-dynamically-convert-dots-to-images-when-filtering-the-carousel-ob/66120825#66120825) and I thought, once the issues with the vignette are solved also the issues described there will be gone. However, they are still here using your latest commit.

Please consider the shiny app below (based on one of your examples). Once the radio button is switched, the new carousel is rendered below the old one:

![screen](https://user-images.githubusercontent.com/36849480/107748993-2d35a600-6d1a-11eb-8867-a6898ef25c16.gif)

Initially I thought it's the same "piling up" problem as seen above, but once I switch `height = 100` to `"25vh"` in `slickR` it's working fine.

We've found a workaround using `renderUI` where `height = 100` isn't causing the "jump".

Furthermore `input$mySlick` isn't providing any data. Is this due to using `customPaging`? (regarding the SO question we've found a JS workaround).

```
library(shiny)
library(htmlwidgets)
library(slickR)

DF <- data.frame(fish = c(
  "https://www.hakaimagazine.com/wp-content/uploads/aquarium-reef-fish-banner.jpg",
  "https://www.hakaimagazine.com/wp-content/uploads/aquarium-reef-fish-banggai-cardinalfish.jpg",
  "https://www.sonomamag.com/wp-content/uploads/2016/12/fish.jpg"
),
butterfly = c(
  "https://www.futurity.org/wp/wp-content/uploads/2019/02/viceroy-butterfly_1600.jpg",
  "https://harvardforest.fas.harvard.edu/sites/harvardforest.fas.harvard.edu/files/butterfly_giant_swallowtail_model.jpg",
  "https://www.butterflyidentification.com/wp-content/uploads/2019/02/Doris-Longwing-Butterfly-Images.jpg"
),
bird = c(
  "http://www.cutepetname.com/wp-content/uploads/2018/11/funy-bird-names-feat-img.jpeg",
  "http://3.bp.blogspot.com/-mJ-Kw1mdLOo/UeLJx7vxsaI/AAAAAAAADkg/TfDHtuJnY7I/s1600/The-Cardinal-Bird.jpg",
  "https://images7.alphacoders.com/416/thumb-1920-416332.jpg"
))

ui <- fluidPage(slickROutput("mySlick", width = "50%"),
                radioButtons(
                  'series',
                  "Choose Series",
                  choices = c(
                    "fish" = "fish",
                    "butterfly" = "butterfly",
                    "bird" = "bird"
                  )
                ),
                textOutput("center"))

server <- function(input, output, session) {
  output$mySlick <- renderSlickR({

    cP2 <- JS(
      paste0("function(slick,index) {
      var dotObj = ", jsonlite::toJSON(DF[[input$series]]),";
          return '<a><img src= ' + dotObj[index] + '  width=100% height=100%></a>';
          }"))
    
    opts_dot_logo <-
      settings(
        initialSlide = 1,
        slidesToShow = 1,
        slidesToScroll = 3,
        centerMode = TRUE,
        focusOnSelect = TRUE,
        dots = TRUE,
        customPaging = cP2
      )
    
    slick_dots_logo <- slickR(obj = DF[[input$series]],
                              height = 100) + opts_dot_logo # "25vh" works fine
    
    
    slick_dots_logo
  })
  
  observeEvent(input$mySlick, {
    print(input$mySlick$.center)
  })
  
  output$center <- renderText({
    paste("Center:", input$mySlick$.center)
  })
  
}

shinyApp(ui, server)
```

**Comment by ismirsehregal** [comment]
Just saw, that the description given in the vignette needs to be aligned with the actual outputs:

.clicked_slide != .clicked etc.

# Using this you can interact server-side "on click" of the active carousel
# by accessing elements in `input$slick_output_current$`

# `.clicked_slide`   : The index of the clicked element|
# `.relative_clicked`: The relative position of the clicked element|
# `.center_slide`    : The index of the center element|
# `.total_slide`     : The total number of elements in the carousel|
# `.active_slide`    : The ID of the active carousel|

# We will store this information in a new reactive environment
active_slick <- shiny::reactiveValues()
  
shiny::observeEvent(input$slick_output_current,{
  
  clicked_slide    <- input$slick_output_current$.clicked
  relative_clicked <- input$slick_output_current$.relative_clicked
  center_slide     <- input$slick_output_current$.center
  total_slide      <- input$slick_output_current$.total
  active_slide     <- input$slick_output_current$.slide

**Comment by yonicd** [comment]
Thanks for the comment 👍

**Comment by ismirsehregal** [comment]
I just realized, that when using https://github.com/yonicd/slickR/commit/417fd60e013b70540970c1b798897050c3580d2c there still is an issue: when stack is selected an we are going back to single both carousels remain.

![screen](https://user-images.githubusercontent.com/36849480/108682588-c91c9a00-74f0-11eb-8276-9e62ff36797b.gif)

**Comment by yonicd** [comment]
you are right. 

the way the js is written only 1 slider is being removed because it is removing based on the number of slicks that are being created and not the existing ones. 

so when moving from 2 to 1 it is looking for only 1. the original code was written assuming you are updating the same number of slicks every time.

**Comment by yonicd** [comment]
this should fix the issue https://github.com/yonicd/slickR/commit/3505e63400bce35a4b321a03bc4c43e3556a42f8

**Comment by yonicd** [comment]
closed with pr https://github.com/yonicd/slickR/pull/56
