### ISSUE TITLE
slickr_output_current$.center isn't providing data on shiny app startup

### ISSUE THREAD

**Issue by ismirsehregal** [yonicd/slickR#53]
Currently `slickr_output_current$.center` isn't providing the carousels center on app start only after the first click.

I think it would be useful to provide the center right away, as done [here](https://stackoverflow.com/a/56002016/9841389).
Please see the following:

![image](https://user-images.githubusercontent.com/36849480/107757237-9373f600-6d25-11eb-875b-04e7a86dd181.png)

```
library(shiny)
library(slickR)

js <- "
$(document).ready(function(){
  $('#slickr').on('setPosition', function(event, slick) {
    var index = slick.currentSlide + 1;
    Shiny.setInputValue('imageIndex', index);
  });
})"

# create some local images
if(!dir.exists("myimages")){
  dir.create("myimages")
}

imgs <- paste0("myimages/myplot", seq_len(3), ".png")

for (img in imgs) {
  png(file = img, bg = "transparent")
  plot(runif(10))
  dev.off() 
}

ui <- fluidPage(
  tags$head(
    tags$script(HTML(js))
  ),
  textOutput("imgName"),
  textOutput("imgIndex"),
  tags$hr(),
  tags$div(
    slickROutput("slickr", width="500px"),
    style = "margin-left:100px;"
  )
)

server <- function(input, output) {
  
  output[["slickr"]] <- renderSlickR({
    slickR(imgs)
  })
  
  output[["imgName"]] <- renderText({
    paste0("CURRENT IMAGE: ", basename(imgs[input[["imageIndex"]]]))
  })
  
  output[["imgIndex"]] <- renderText({
    paste0("slickr_current$.center: ", input$slickr_current$.center)
  })
  
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by yonicd** [comment]
Information is observed onclick of the slick in the JavaScript side

**Comment by ismirsehregal** [comment]
Sure and this makes sense for the output of `.clicked` and `.relative_clicked` but 

- `.center`
- `.total`
- `.active`

could be initialized right after rendering. This would make things easier regarding the initialization of downstream reactives.

**Comment by yonicd** [comment]
thanks for the suggestion. 

you are welcome to create a PR for this enhancement, it is not top priority for me currently.
