### ISSUE TITLE
Move previous next buttons

### ISSUE THREAD

**Issue by ixodid198** [yonicd/slickR#59]
I can successfully move the "next" button for slickR's carousel. However, when I use the similar method to move the "previous" button it does not work. The action and the mouseover no longer work. Why is this? How can I move the "prev" button and maintain full functionality?

Here is where the fully functional moved buttons should appear: 
![Screen Shot 2021-06-01 at 5 00 03 PM](https://user-images.githubusercontent.com/12522241/120392124-0a95c000-c2fe-11eb-8a53-c2cfa3cdef0e.png)

```
library(shiny)
library(slickR)

# Test #########################################################################
chart_names_list <- c( "http://placehold.it/900x500/39CCCC/ffffff&text=Slide+1", 
                                                "http://placehold.it/900x500/39CCCC/ffffff&text=Slide+2",
                                                "http://placehold.it/900x500/39CCCC/ffffff&text=Slide+3")
num_slides <- 2


ui <- fluidPage(
  tags$head(
    tags$style(HTML("
    .slick-next {
      right: 163px;
      top: 20px;
    }
    .slick-prev {
      left: 670px;
      top: 20px;
    }
    .slick-slide {
      margin-top: 30px;
    }
      
    ")
    )
  ),
  
  slickROutput("slick_output")
)

server <- function(input, output, session) {
  output$slick_output <- renderSlickR({
    slickR(obj = chart_names_list, height = 300, width = "100%") +
      settings(dots = TRUE)
  })
}

shinyApp(ui, server)
```

**Comment by yonicd** [comment]
the arrows are set within the htmlwidget. i dont think in this version you can move them around. 

https://github.com/yonicd/slickR/blob/master/inst/htmlwidgets/lib/slickR/slickR.js#L90_L138

**Comment by ixodid198** [comment]
Thanks for looking into this. But isn't it odd though that the "next" button can be moved successfully and not the "prev" button?

**Comment by ismirsehregal** [comment]
Related SO questions for future readers:

https://stackoverflow.com/questions/67782004/move-previous-next-buttons-in-rs-slickr-carousel/
https://stackoverflow.com/questions/67841891/make-slickr-carousel-responsive/

**Comment by yonicd** [comment]
thanks for the links! closing this issue here.
