### ISSUE TITLE
SlickR and Shiny, duplicated carousels

### ISSUE THREAD

**Issue by cschwem2er** [yonicd/slickR#70]
Hi,

thanks for creating this package! :) I am currently trying to set up a shiny app where users can inspect (random) images in a carousel, and after clicking a button, the carousel loads with new images.

Unfortunately, this does not work. Shiny adds another carousel below instead of replacing the existing one. See here as an example: 

![image](https://user-images.githubusercontent.com/7460499/210253880-a56e4765-db3a-46d2-a434-abf091b18bbe.png)

My setup looks roughly like this:

```

library(shiny)
library(tidyverse)
library(slickR)

# Define UI for app that draws a histogram ----
ui <- fluidPage(

    mainPanel(
     
      slickROutput("slickr", width="100%"),
      
      actionButton("submit", "An action button")
      
    )
 # )
)

server <- function(input, output) {
  
 load_random_images <- function(x) {
## some function to load a number of random images
}

  
  output$slickr <- renderSlickR({
    input$submit
  
    
    image_paths  <- load_randon_images()

    slickR(image_paths, height = 400, width = "100%",
           padding = 0) + 
      settings(dots = TRUE, infinite = FALSE,
               slidesToShow =  1,
               centerMode =FALSE,
              adaptiveHeight = TRUE)   
  })
  
}

shinyApp(ui = ui, server = server)

```
Do you know how to solve this problem?

**Comment by yonicd** [comment]
In your `slickr` call set the `slideId` to something static, else a random hash is used to avoid conflicts between sliders.

see [vignette](https://yonicd.github.io/slickR/articles/shiny.html) for an example

**Comment by cschwem2er** [comment]
Hi, thanks for your fast response, but adjusting the code as such does not solve the problem:
``
    slickR(image_paths, height = 400, width = "100%",
           padding = 0, slideId = "1337"))
``

**Comment by yonicd** [comment]
You are right. There is a new problem in the underlying js. I will look into it. Thanks for raising this issue!

**Comment by yonicd** [comment]
this patch should fix it https://github.com/yonicd/slickR/commit/625d34072aa1e9e9b0ede9ffedcc0b0c2bd23fbc, let me know if it works for you.

**Comment by LaytonWashburn** [comment]
I am also getting duplications when using slickR in shiny. Is there a fix for this?
